version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgresql://postgres:example@db:5432/saas_app
      JWT_SECRET: your_jwt_secret
      STRIPE_SECRET_KEY: your_stripe_secret_key
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: saas_app
    ports:
      - '5432:5432'